version: '3.8'

services:
  px4-dev-ros-1:
    image: njbrown09/lm01-drone-sar:latest
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - PX4_HOME_LAT=42.3898
      - PX4_HOME_LON=-71.1476
      - PX4_HOME_ALT=14.2
      - PX4_SIM_HOST_ADDR=172.23.0.1
      - MAVLINK_TCP_PORT=4560
      - MAVLINK_UDP_PORT=14560
      - MAVLINK_ID=1
      - DISPLAY=:0
    volumes:
      - /mnt/c/Users/Admin/Documents/Colosseum/PX4/PX4-Autopilot:/src/PX4-Autopilot:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ports:
      - "14570:14570/udp"
      - "5760:5760/tcp"
    networks:
      - px4_network
      
  px4-dev-ros-2:
    image: njbrown09/lm01-drone-sar:latest
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - PX4_HOME_LAT=42.3898
      - PX4_HOME_LON=-71.1476
      - PX4_HOME_ALT=14.2
      - PX4_SIM_HOST_ADDR=172.23.0.1
      - MAVLINK_TCP_PORT=4561
      - MAVLINK_UDP_PORT=14561
      - MAVLINK_ID=2
      - DISPLAY=:0
    volumes:
      - /mnt/c/Users/Admin/Documents/Colosseum/PX4/PX4-Autopilot:/src/PX4-Autopilot:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ports:
      - "14571:14571/udp"
      - "5761:5761/tcp"
    networks:
      - px4_network

networks:
  px4_network:
    driver: bridge
